# Generated by Django 3.1 on 2020-09-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
        ('property_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_int', models.DateField(verbose_name='check_int')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check_out')),
                ('book_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_book.property_book', verbose_name='Property_book')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalemployee', verbose_name='employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.readerticket', verbose_name='library_card')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journal',
                'db_table': 'Journal',
            },
        ),
    ]
