# Generated by Django 3.1 on 2020-09-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'journal', 'verbose_name_plural': 'journal'},
        ),
        migrations.AlterModelTable(
            name='journal',
            table='journals',
        ),
    ]
