# Generated by Django 3.1 on 2020-09-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200904_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalemployee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
