# Generated by Django 3.1 on 2020-09-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre', models.CharField(max_length=30, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'genre book',
                'verbose_name_plural': 'genre books',
                'db_table': 'Genries_book',
            },
        ),
        migrations.CreateModel(
            name='BooksAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author', models.CharField(help_text='Full Name', max_length=30, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Author book',
                'verbose_name_plural': 'Author books',
                'db_table': 'Authors_book',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('author', models.ManyToManyField(blank=True, to='books.BooksAuthor')),
                ('genre', models.ManyToManyField(blank=True, to='books.BookGenre')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'Books',
            },
        ),
    ]
