# Generated by Django 3.1 on 2020-09-03 22:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=58, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
                'db_table': 'readers',
            },
        ),
        migrations.CreateModel(
            name='ReaderTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10, verbose_name='Library card')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Reader ticket',
                'verbose_name_plural': 'Reader tickets',
                'db_table': 'Readers ticket',
            },
        ),
        migrations.CreateModel(
            name='ReaderPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'reader phone',
                'verbose_name_plural': 'reader phones',
                'db_table': 'readers_phone',
            },
        ),
        migrations.CreateModel(
            name='ReaderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_reader', models.CharField(max_length=15, verbose_name='City')),
                ('street_reader', models.CharField(max_length=15, verbose_name='Street')),
                ('house_reader', models.CharField(help_text='Only number house and number apartments', max_length=15, verbose_name='Number house and number apartments')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Reader Address',
                'verbose_name_plural': 'Reader addresses',
                'db_table': 'readers_Address',
            },
        ),
    ]
