# Generated by Django 3.1 on 2020-09-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerticket',
            name='valid_until',
            field=models.DateField(default='2020-05-07', verbose_name='Valid until'),
        ),
    ]
