# Generated by Django 3.1 on 2020-09-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_readerticket_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerticket',
            name='valid_until',
            field=models.DateField(verbose_name='Valid until'),
        ),
    ]
