# Generated by Django 3.1 on 2020-09-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_auto_20200904_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'reader', 'verbose_name_plural': 'readers'},
        ),
        migrations.AlterModelOptions(
            name='readeraddress',
            options={'verbose_name': 'reader_address', 'verbose_name_plural': 'reader_addresses'},
        ),
        migrations.AlterModelOptions(
            name='readerphone',
            options={'verbose_name': 'reader_phone', 'verbose_name_plural': 'reader_phones'},
        ),
        migrations.AlterModelOptions(
            name='readerticket',
            options={'verbose_name': 'reader ticket', 'verbose_name_plural': 'reader tickets'},
        ),
        migrations.AlterModelTable(
            name='readeraddress',
            table='readers_address',
        ),
        migrations.AlterModelTable(
            name='readerticket',
            table='readers ticket',
        ),
    ]
