# Generated by Django 3.1 on 2020-09-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_auto_20200904_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readeraddress',
            options={'verbose_name': 'reader address', 'verbose_name_plural': 'reader addresses'},
        ),
        migrations.AlterModelOptions(
            name='readerphone',
            options={'verbose_name': 'reader phone', 'verbose_name_plural': 'reader phones'},
        ),
        migrations.AlterModelTable(
            name='readeraddress',
            table='readers address',
        ),
        migrations.AlterModelTable(
            name='readerphone',
            table='readers phone',
        ),
    ]
