# Generated by Django 3.1 on 2020-09-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_auto_20200904_0300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='readerphone',
            table='readers_phone',
        ),
    ]
