# Generated by Django 3.1 on 2020-09-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0006_auto_20200908_0352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='readeraddress',
            table='readers_address',
        ),
        migrations.AlterModelTable(
            name='readerticket',
            table='readers_ticket',
        ),
    ]
