# Generated by Django 3.1 on 2020-09-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property_book',
            options={'verbose_name': 'property Book', 'verbose_name_plural': 'property Books'},
        ),
        migrations.AlterModelOptions(
            name='property_publishing_house',
            options={'verbose_name': 'publisher', 'verbose_name_plural': 'publishing house'},
        ),
        migrations.AlterModelOptions(
            name='property_status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'property Status'},
        ),
        migrations.AlterModelTable(
            name='property_book',
            table='property_books',
        ),
        migrations.AlterModelTable(
            name='property_publishing_house',
            table='publishing_house',
        ),
        migrations.AlterModelTable(
            name='property_status',
            table='property_status',
        ),
    ]
